# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-05 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='btitle',
            field=models.CharField(help_text='图书名称', max_length=20, verbose_name='名称'),
        ),
    ]
